version: "3.9"
services:
  db:
    image: postgres:15
    container_name: game-localization-db
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: localizationdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
