server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public";
  }

  location / {
    try_files $uri /index.html;
  }

  gzip on;
  gzip_types text/plain application/javascript application/json text/css text/xml application/xml+rss image/svg+xml;
  gzip_min_length 256;
}
